### ISSUE TITLE
画像のライセンスを明記する

### ISSUE THREAD

**Issue by igrep** [haskell-jp/logo#3]
普通にCC-BYでいいと思うけど、細かいところを詰める必要があるので保留。

**Comment by fumieval** [comment]
個人的にはCC-BY-SAと同等以上の強さが欲しいです

**Comment by igrep** [comment]
@fumieval なるほど。どんな理由ですかね？

個別に設定した方がいいのかな。。。

**Comment by fumieval** [comment]
派生を作ったりする分には構わないのですが、改変後のものにより制約の強いライセンスが適用されるのはあまり望ましくないです。CC-BY-SAでもロゴにしては非常に緩いほうだと思います。

**Comment by igrep** [comment]
了解です。ライセンスはCC-BY-SA（か、それ以上）でよいとして、
名義については希望がありますか？
Fumiaki Kinoshita か Haskell-jp と書くか二通り考えられると思います。
個人的には、Fumiaki Kinoshita で多分問題ないと思っています。

**Comment by fumieval** [comment]
どちらでも構いませんが、私の名前でいいということならそれで！
